version: "3.8"
services:
  shopmap-postgres-db:
    container_name: shopmap-postgres-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shop_map
  shopmap-backend:
    container_name: shopmap-backend
    image: bendricks/shopmap-back
    depends_on:
      - shopmap-postgres-db
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://shopmap-postgres-db:5432/shop_map
      - MYAPP_JDBC_USER=postgres
      - MYAPP_JDBC_PASS=password
      - MYAPP_CORS_URL=http://localhost
  shopmap-frontend:
    container_name: shopmap-frontend
    image: bendricks/shopmap-front
    depends_on:
      - shopmap-backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8393
      - WDS_SOCKET_PORT=0
  nginx_proxy:
    build: /nginx_proxy
    depends_on:
      - shopmap-backend
      - shopmap-frontend
    ports:
      - "80:80"
      - "8393:8393"